### ISSUE TITLE
No matter what i do, print_logo doesn't work

### ISSUE THREAD

**Issue by JerramyKing** [yusent/pos-printer#2]
Every time I try to add a picture/logo, nothing happens. 
The print_logo function doesn't work for me, maybe I'm doing it wrong, but when I add just 'print_logo' nothing happens, so I add something for it to print, a link or a file path or something like that, I get an error saying 'The wrong number of arguments given, expected 0 got 1'
So I'm not supposed to give it anything to print (how is it supposed to know what I want to print???) and if I do, I get an error, has anybody else gotten this? What do I do to get an image to work?

**Comment by yusent** [comment]
POS printers usually come with a software that allows you to store a logo in the printer's memory. `print_logo` method simply sends a command to the printer for printing the previously stored logo.

e.g. Here are the instructions for a Bixolon printer: https://bixolonusa.com/faq-items/setting-logo-printing-9/

**Comment by domanwa** [comment]
@yusent does this printer still work? 

```
LoadError (cannot load such file -- pos-printer)
```
This is after installing the gem :confused:

**Comment by yusent** [comment]
@domanwa Sorry for the late response. I didn't see the notification for your message and I'm not actively working on this project.

It seems like your issue was regarding your load path. Feel free to reach out through a new issue if you still need help.
